ALTER TABLE "analytics_snapshots" DROP CONSTRAINT "analytics_snapshots_known_metric";
ALTER TABLE "analytics_snapshots" ADD CONSTRAINT "analytics_snapshots_known_metric" CHECK ("metric_key" IN (
  'APPOINTMENTS_TOTAL', 'CANCELLATIONS_TOTAL', 'NO_SHOWS_TOTAL', 'UNCONFIRMED_TOTAL',
  'ACTIVE_WAITLIST_TOTAL', 'FAILED_MESSAGES_TOTAL', 'OPEN_HANDOFFS_TOTAL',
  'MISSED_CALLS_TOTAL', 'SCHEDULE_GAPS_TOTAL', 'SCHEDULED_MINUTES'
));
